services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres_db
    volumes:
      - "vol-postgres:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "vol-pgadmin:/var/lib/pgadmin"
    ports:
      - "8085:80"

volumes:
  vol-postgres:
    name: vol-postgres
  vol-pgadmin:
    name: vol-pgadmin
